### ISSUE TITLE
pyopenjtalk cannot be installed in google colab

### ISSUE THREAD

**Issue by kan-bayashi** [r9y9/pyopenjtalk#27]
Recently, it seems that pyopenjtalk cannot be installed in google colab.

```
!pip install -vvv pyopenjtalk==0.1.5

Using pip 21.3.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-u03ax74j
Created temporary directory: /tmp/pip-req-tracker-h07x85zq
Initialized build tracking at /tmp/pip-req-tracker-h07x85zq
Created build tracker: /tmp/pip-req-tracker-h07x85zq
Entered build tracker: /tmp/pip-req-tracker-h07x85zq
Created temporary directory: /tmp/pip-install-xzagbojv
1 location(s) to search for versions of pyopenjtalk:
* https://pypi.org/simple/pyopenjtalk/
Fetching project page and analyzing links: https://pypi.org/simple/pyopenjtalk/
Getting page https://pypi.org/simple/pyopenjtalk/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pyopenjtalk/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pyopenjtalk/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/a9/54/5e321e9dd690847b37e3e7abba67b263b37462ab08ed6849eebdf409492a/pyopenjtalk-0.0.1.tar.gz#sha256=e90125fe9b418c95efb229f7680900b34834cf522e2630fcf96be99c4cf93fcc (from https://pypi.org/simple/pyopenjtalk/), version: 0.0.1
  Found link https://files.pythonhosted.org/packages/2b/ca/b34640163fa2962222f3cf8fc1e3d2e3e287323253b49117e54ea3ab7789/pyopenjtalk-0.0.2.tar.gz#sha256=bc8795dbcb3d607a6d406574461755286dc40377ed474fed4b43c785bef6165c (from https://pypi.org/simple/pyopenjtalk/), version: 0.0.2
  Found link https://files.pythonhosted.org/packages/53/d7/b026f0d84b0f0c4c07e0f052adf8a1396b8998806b48c34b49bd44d9f46e/pyopenjtalk-0.0.3.tar.gz#sha256=aae915c29311c07df291119818b72a693da8adbc2a0f1c1d2e6b84d6f80669c2 (from https://pypi.org/simple/pyopenjtalk/), version: 0.0.3
  Found link https://files.pythonhosted.org/packages/6a/77/5567ee3621ee0dc4573a44a3dfe2da56f3efea3e6d86907368369aa9fd79/pyopenjtalk-0.1.0.tar.gz#sha256=f7a07be4e9ffafdbe46086a365edd54007b3358e33f6d843f37136319b55b433 (from https://pypi.org/simple/pyopenjtalk/), version: 0.1.0
  Found link https://files.pythonhosted.org/packages/8c/a6/abf6d0e4b698dd9ec827af5bc70f1e133f7bdc12d258dae82360bd8003bb/pyopenjtalk-0.1.1.tar.gz#sha256=18c859e146da21cba44ad7c2d3526ed02d9a50e8e5d85c8e37de74f59f22e95e (from https://pypi.org/simple/pyopenjtalk/), version: 0.1.1
  Found link https://files.pythonhosted.org/packages/34/38/2ca282ca63da6d5d8fb45e7fe18bb772cfcd310b4c7329b5a855c982b5b2/pyopenjtalk-0.1.2.tar.gz#sha256=0ed853b7e778a1ca7f241de0547b2bf73e5a9804925239da9076da9613b3aebd (from https://pypi.org/simple/pyopenjtalk/), version: 0.1.2
  Found link https://files.pythonhosted.org/packages/f3/2a/58297ac067c9f5688081569cf9c3ee8e9514b6beba2f4224d60ca40bb6d2/pyopenjtalk-0.1.3.tar.gz#sha256=6072ef8de7ae13013d3a72bf4a18783cb24aa74a241ee4c155d2e16b0bd1b9ad (from https://pypi.org/simple/pyopenjtalk/), version: 0.1.3
  Found link https://files.pythonhosted.org/packages/ef/73/59ffe743d2b36ddc50907e643e3cca3ae3f141d5cf977a5cb4339a79a259/pyopenjtalk-0.1.4.tar.gz#sha256=deee7877f71f6f611d9aa3c287b1db24cbca27db37c48f2dee901dafce514724 (from https://pypi.org/simple/pyopenjtalk/), version: 0.1.4
  Found link https://files.pythonhosted.org/packages/0c/b7/b39a0eacdb267fbb2a77c6d155dc76c414f20455295c9a2026a05ff3c8ec/pyopenjtalk-0.1.5.tar.gz#sha256=3e1e3788a0bb060167d8e470adc0f254c9782df9e28c95497ed9f8e8fe8b38a3 (from https://pypi.org/simple/pyopenjtalk/), version: 0.1.5
Skipping link: not a file: https://pypi.org/simple/pyopenjtalk/
Given no hashes to check 1 links for project 'pyopenjtalk': discarding no candidates
Collecting pyopenjtalk==0.1.5
  Created temporary directory: /tmp/pip-unpack-0yexhuyt
  Looking up "https://files.pythonhosted.org/packages/0c/b7/b39a0eacdb267fbb2a77c6d155dc76c414f20455295c9a2026a05ff3c8ec/pyopenjtalk-0.1.5.tar.gz" in the cache
  Current age based on date: 1135
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 1135
  Using cached pyopenjtalk-0.1.5.tar.gz (1.5 MB)
  Added pyopenjtalk==0.1.5 from https://files.pythonhosted.org/packages/0c/b7/b39a0eacdb267fbb2a77c6d155dc76c414f20455295c9a2026a05ff3c8ec/pyopenjtalk-0.1.5.tar.gz#sha256=3e1e3788a0bb060167d8e470adc0f254c9782df9e28c95497ed9f8e8fe8b38a3 to build tracker '/tmp/pip-req-tracker-h07x85zq'
  Created temporary directory: /tmp/pip-build-env-cdfmoobc
  Created temporary directory: /tmp/pip-standalone-pip-yr0cw4g6
  Running command /usr/bin/python3 /tmp/pip-standalone-pip-yr0cw4g6/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-cdfmoobc/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'cython>=0.21.0' 'numpy<v1.20.0'
  Using pip 21.3.1 from /tmp/pip-standalone-pip-yr0cw4g6/__env_pip__.zip/pip (python 3.7)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting setuptools
    Using cached setuptools-60.5.0-py3-none-any.whl (958 kB)
  Collecting cython>=0.21.0
    Using cached Cython-0.29.26-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
    Link requires a different Python (3.7.12 not in: '>=3.8'): https://files.pythonhosted.org/packages/7a/7f/5384d4c85a2349bd89ff1c0253bff77c7b617e48af201f2d823fc619189a/numpy-1.22.0rc1.zip#sha256=bc991b3f8ea7c0f6703df2bc23c098cfe6f1a3a5e8a3a901eb6a5619275d53ff (from https://pypi.org/simple/numpy/) (requires-python:>=3.8)
    Link requires a different Python (3.7.12 not in: '>=3.8'): https://files.pythonhosted.org/packages/a1/4a/8fd68d9a0a9fe5419cdbb697ffc96259fb716bd952c5c64225991add7551/numpy-1.22.0rc2.zip#sha256=01810dc32c5ac4c895b5c0d285497e1eb52038834919f3d2eaddfb9526b20dc9 (from https://pypi.org/simple/numpy/) (requires-python:>=3.8)
    Link requires a different Python (3.7.12 not in: '>=3.8'): https://files.pythonhosted.org/packages/17/d4/d3ac79fca81154e8d3e11232967024f480cfdc87dfeef479803716fb20cb/numpy-1.22.0rc3.zip#sha256=0b5642efe2a36f2191102b44bb95ee1479f14c1adb2d7155303e50b2517e43bc (from https://pypi.org/simple/numpy/) (requires-python:>=3.8)
    Link requires a different Python (3.7.12 not in: '>=3.8'): https://files.pythonhosted.org/packages/50/e1/9b0c184f04b8cf5f3c941ffa56fbcbe936888bdac9aa7ba6bae405ac752b/numpy-1.22.0.zip#sha256=a955e4128ac36797aaffd49ab44ec74a71c11d6938df83b1285492d277db5397 (from https://pypi.org/simple/numpy/) (requires-python:>=3.8)
    Link requires a different Python (3.7.12 not in: '>=3.8'): https://files.pythonhosted.org/packages/0a/c8/a62767a6b374a0dfb02d2a0456e5f56a372cdd1689dbc6ffb6bf1ddedbc0/numpy-1.22.1.zip#sha256=e348ccf5bc5235fc405ab19d53bec215bb373300e5523c7b476cc0da8a5e9973 (from https://pypi.org/simple/numpy/) (requires-python:>=3.8)
  Collecting numpy<v1.20.0
    Using cached numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
  Installing collected packages: wheel, setuptools, numpy, cython
    Creating /tmp/pip-build-env-cdfmoobc/overlay/bin
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/wheel to 755
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/f2py to 755
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/f2py3 to 755
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/f2py3.7 to 755
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/cygdb to 755
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/cython to 755
    changing mode of /tmp/pip-build-env-cdfmoobc/overlay/bin/cythonize to 755
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
  albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
  Successfully installed cython-0.29.26 numpy-1.19.5 setuptools-60.5.0 wheel-0.37.1
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies ... done
  Running command /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqdjkah8t
  AttributeError: DistutilsMetaFinder instance has no attribute 'find_module'
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 154, in <module>
    File "/usr/lib/python3.7/subprocess.py", line 444, in check_returncode
      self.stderr)
  subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
  Getting requirements to build wheel ... error
WARNING: Discarding https://files.pythonhosted.org/packages/0c/b7/b39a0eacdb267fbb2a77c6d155dc76c414f20455295c9a2026a05ff3c8ec/pyopenjtalk-0.1.5.tar.gz#sha256=3e1e3788a0bb060167d8e470adc0f254c9782df9e28c95497ed9f8e8fe8b38a3 (from https://pypi.org/simple/pyopenjtalk/). Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqdjkah8t Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyopenjtalk==0.1.5 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
ERROR: No matching distribution found for pyopenjtalk==0.1.5
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('pyopenjtalk==0.1.5')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 351, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('pyopenjtalk==0.1.5'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 339, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pyopenjtalk==0.1.5
Removed pyopenjtalk==0.1.5 from https://files.pythonhosted.org/packages/0c/b7/b39a0eacdb267fbb2a77c6d155dc76c414f20455295c9a2026a05ff3c8ec/pyopenjtalk-0.1.5.tar.gz#sha256=3e1e3788a0bb060167d8e470adc0f254c9782df9e28c95497ed9f8e8fe8b38a3 from build tracker '/tmp/pip-req-tracker-h07x85zq'
Removed build tracker: '/tmp/pip-req-tracker-h07x85zq'
```

Related version info
```
!python --version
!gcc -v
!cmake --version

Python 3.7.12
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
cmake version 3.12.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Reproducible notebook gist: https://gist.github.com/kan-bayashi/8d1a7973cbe0ad15375c995e50c8e8b2

Related: https://github.com/espnet/espnet/discussions/4001

**Comment by r9y9** [comment]
Thanks for your report! I confirmed I can reproduce the issue. 

```
  AttributeError: DistutilsMetaFinder instance has no attribute 'find_module'
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python3.7/dist-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 154, in <module>
    File "/usr/lib/python3.7/subprocess.py", line 444, in check_returncode
      self.stderr)
  subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
```

So far I suspect the issue comes from setuptools/pip changes.  It is strange that ` cmake .. -DHTS_ENGINE_INCLUDE_DIR=. -DHTS_ENGINE_LIB=dummy` works without problem on google colab if I manually run the command on shell. So there's no problem with cmake and C/C++ compiler. I am going to look into the issue carefully when I have time.

**Comment by r9y9** [comment]
I got the workaround #28 

@kan-bayashi Could you check if it works for you? Also, please let me know if you want me to tag a new version.

Here's the command you can try:

```
pip install git+https://github.com/r9y9/pyopenjtalk.git@workaround-setuptools-issue
```

**Comment by kan-bayashi** [comment]
It seems working!
```
!pip install git+https://github.com/r9y9/pyopenjtalk.git@workaround-setuptools-issue
Collecting git+https://github.com/r9y9/pyopenjtalk.git@workaround-setuptools-issue
  Cloning https://github.com/r9y9/pyopenjtalk.git (to revision workaround-setuptools-issue) to /tmp/pip-req-build-yf7cdz8w
  Running command git clone -q https://github.com/r9y9/pyopenjtalk.git /tmp/pip-req-build-yf7cdz8w
  Running command git checkout -b workaround-setuptools-issue --track origin/workaround-setuptools-issue
  Switched to a new branch 'workaround-setuptools-issue'
  Branch 'workaround-setuptools-issue' set up to track remote branch 'workaround-setuptools-issue' from 'origin'.
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cython>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from pyopenjtalk==0.1.6+03aa3a1) (0.29.26)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from pyopenjtalk==0.1.6+03aa3a1) (4.62.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from pyopenjtalk==0.1.6+03aa3a1) (1.15.0)
Requirement already satisfied: numpy>=1.8.0 in /usr/local/lib/python3.7/dist-packages (from pyopenjtalk==0.1.6+03aa3a1) (1.19.5)
Building wheels for collected packages: pyopenjtalk
  Building wheel for pyopenjtalk (PEP 517) ... done
  Created wheel for pyopenjtalk: filename=pyopenjtalk-0.1.6+03aa3a1-cp37-cp37m-linux_x86_64.whl size=4432226 sha256=1bde25e2491a767b03641784bca6c30c5bc449f2e0c8d86e1024c155e59f70a7
  Stored in directory: /tmp/pip-ephem-wheel-cache-vzdg5ysz/wheels/f0/34/68/d3a566b0ef36cf93ff79fbb9e7a0c18603dec98913dccd62ae
Successfully built pyopenjtalk
Installing collected packages: pyopenjtalk
Successfully installed pyopenjtalk-0.1.6+03aa3a1
```

**Comment by kan-bayashi** [comment]
```
!pip install -U setuptools==v59.8
!pip install pyopenjtalk==0.1.5

Requirement already satisfied: setuptools==v59.8 in /usr/local/lib/python3.7/dist-packages (59.8.0)
Collecting pyopenjtalk==0.1.5
  Using cached pyopenjtalk-0.1.5.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
WARNING: Discarding https://files.pythonhosted.org/packages/0c/b7/b39a0eacdb267fbb2a77c6d155dc76c414f20455295c9a2026a05ff3c8ec/pyopenjtalk-0.1.5.tar.gz#sha256=3e1e3788a0bb060167d8e470adc0f254c9782df9e28c95497ed9f8e8fe8b38a3 (from https://pypi.org/simple/pyopenjtalk/). Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.7/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp5yr5ttig Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyopenjtalk==0.1.5 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
ERROR: No matching distribution found for pyopenjtalk==0.1.5
```
This does not work 🤔 What is the difference...?

**Comment by r9y9** [comment]
Yeah it's expected behavior. When you run `pip install pyopenjtalk`, pip will create an isolated python env (like virtualenv) for building the package based on pyproject.toml https://github.com/r9y9/pyopenjtalk/blob/7ad3adc358a4348434844db55b8f181c713c99c7/pyproject.toml#L1-L7

Therefore, it is necessary to change the build-time requirements as done in #28.

See https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/ for details

> Build Isolation
For building packages using this interface, pip uses an isolated environment. That is, pip will install build-time Python dependencies in a temporary directory which will be added to sys.path for the build commands. This ensures that build requirements are handled independently of the user’s runtime environment.

**Comment by kan-bayashi** [comment]
I see! Thank you for your kind explanation!
Could you release it as 0.1.5.post1 or 0.1.6?

**Comment by r9y9** [comment]
Great! I will tag a new release soon.

**Comment by kan-bayashi** [comment]
I really appreciate your quick fixing. Thank you so much!
