### ISSUE TITLE
Fail to pip install in M1 platform

### ISSUE THREAD

**Issue by kimyLee** [r9y9/pyopenjtalk#49]
use python 3.10, and error is like:
 
 (py30) zhonghaoli@MacBook-Pro-14-inch-2021 ChatWaifu % pip install openjtalk
Defaulting to user installation because normal site-packages is not writeable
Collecting openjtalk
  Using cached openjtalk-0.3.0.dev3.tar.gz (24.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/15/15/fb29ebea31d9b0fbe72b8547c9221dda17df8e23e3b4f2eb326eec07966a/openjtalk-0.3.0.dev3.tar.gz (from https://pypi.org/simple/openjtalk/): Requested openjtalk from https://files.pythonhosted.org/packages/15/15/fb29ebea31d9b0fbe72b8547c9221dda17df8e23e3b4f2eb326eec07966a/openjtalk-0.3.0.dev3.tar.gz has inconsistent version: expected '0.3.0.dev3', but metadata has '0.3.0'
  Using cached openjtalk-0.3.0.dev2.tar.gz (24.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/zhonghaoli/miniforge3/envs/py30/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/zhonghaoli/miniforge3/envs/py30/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/zhonghaoli/miniforge3/envs/py30/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/2w/pbk90zld77qff4njdw577l780000gn/T/pip-build-env-009lhacz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/2w/pbk90zld77qff4njdw577l780000gn/T/pip-build-env-009lhacz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2w/pbk90zld77qff4njdw577l780000gn/T/pip-build-env-009lhacz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/2w/pbk90zld77qff4njdw577l780000gn/T/pip-build-env-009lhacz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 17, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by RogerAllenDu** [comment]
Getting the same error on Windows. Did you solve it?

**Comment by sabonerune** [comment]
This repository is [pyopenjtalk](https://pypi.org/project/pyopenjtalk/).
But it looks like you are trying to install [openjtalk](https://pypi.org/project/openjtalk/).

The Project description is the same as pyopenjtalk, but the maintainer seems to be different.
