### ISSUE TITLE
Can't use mingw32-make.exe to compile

### ISSUE THREAD

**Issue by Spr-Aachen** [r9y9/pyopenjtalk#68]
Dear author, sorry to interrupt.
I'm using MinGW's make instead of Microsoft's nmake, so I ran `set CMAKE_MAKE_PROGRAM=C:\path\to\mingw\mingw32-make.exe` command before the installation.
However, I still encountered the error below:
```
Collecting pyopenjtalk
  Downloading pyopenjtalk-0.3.2.tar.gz (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 287.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      CMake Error at CMakeLists.txt:17 (project):
        Running

         'nmake' '-?'

        failed with:

         绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.27.2

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "D:\Projekt\AI\Conda\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Projekt\AI\Conda\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Projekt\AI\Conda\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Spr_Aachen\AppData\Local\Temp\pip-build-env-q1dezv3h\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\Spr_Aachen\AppData\Local\Temp\pip-build-env-q1dezv3h\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\Spr_Aachen\AppData\Local\Temp\pip-build-env-q1dezv3h\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "D:\Projekt\AI\Conda\lib\subprocess.py", line 460, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
Any ideas?

**Comment by Spr-Aachen** [comment]
And by the way, I tried using `set CMAKE_C_COMPILER=C:\path\to\mingw\gcc.exe` and `set CMAKE_CXX_COMPILER=C:\path\to\mingw\g++.exe`, but the error still occurred.
